### ISSUE TITLE
Feature flag metal: Fails to load model when n_gpu_layers > 0

### ISSUE THREAD

**Issue by phudtran** [mdrokz/rust-llama.cpp#18]
Can't utilize GPU on Mac with
```
llama_cpp_rs = { git = "https://github.com/mdrokz/rust-llama.cpp", version = "0.3.0", features = [
    "metal",
] }
```
Code
```
use llama_cpp_rs::{
    options::{ModelOptions, PredictOptions},
    LLama,
};
fn main() {
    let model_options = ModelOptions {
        n_gpu_layers: 1,
        ..Default::default()
    };

    let llama = LLama::new("zephyr-7b-alpha.Q2_K.gguf".into(), &model_options);
    println!("llama: {:?}", llama);
    let predict_options = PredictOptions {
        tokens: 0,
        threads: 14,
        top_k: 90,
        top_p: 0.86,
        token_callback: Some(Box::new(|token| {
            println!("token1: {}", token);

            true
        })),
        ..Default::default()
    };

    llama
        .unwrap()
        .predict(
            "what are the national animals of india".into(),
            predict_options,
        )
        .unwrap();
}
```

Error

```
llama_new_context_with_model: kv self size  =   64.00 MB
llama_new_context_with_model: ggml_metal_init() failed
llama: Err("Failed to load model")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to load model"', src/main.rs:40:10
stack backtrace:
   0:        0x1028cc640 - std::backtrace_rs::backtrace::libunwind::trace::h35c35bd6a1eea1a3
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1028cc640 - std::backtrace_rs::backtrace::trace_unsynchronized::h6e6a37fdc09ec2da
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1028cc640 - std::sys_common::backtrace::_print_fmt::h6ae2889d87a644d1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x1028cc640 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb75be2413dd8ceb3
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1028dede0 - core::fmt::rt::Argument::fmt::hfc9103857ff63de2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:        0x1028dede0 - core::fmt::write::h95d50546e769656f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:        0x1028ca958 - std::io::Write::write_fmt::hce019ca594763835
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:        0x1028cc494 - std::sys_common::backtrace::_print::h15dce0f07dfee3db
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x1028cc494 - std::sys_common::backtrace::print::hae7307dcada41b2a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x1028cd770 - std::panicking::default_hook::{{closure}}::h30c41986d637ef23
  10:        0x1028cd578 - std::panicking::default_hook::h81d03189ef2e7e78
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:        0x1028cdbe0 - std::panicking::rust_panic_with_hook::he8360f4d28da55fc
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:        0x1028cdaec - std::panicking::begin_panic_handler::{{closure}}::he9e07d605072520f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:597:13
  13:        0x1028cca20 - std::sys_common::backtrace::__rust_end_short_backtrace::he03bf52f9c1eb73a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:        0x1028cd860 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:        0x1028f1708 - core::panicking::panic_fmt::ha5f5ca2311fff2ad
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:        0x1028f19ac - core::result::unwrap_failed::h34067e5e60f3683e
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
  17:        0x102847704 - ai_arcade::main::h004bf7a5c10e6a22
  18:        0x10284797c - std::sys_common::backtrace::__rust_begin_short_backtrace::hcbda301bd7503965
  19:        0x102847944 - std::rt::lang_start::{{closure}}::hfa2e67c989be46dc
  20:        0x1028c8314 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0689b9cc840db667
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:284:13
  21:        0x1028c8314 - std::panicking::try::do_call::h8d21b0c0c04af112
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  22:        0x1028c8314 - std::panicking::try::h618481d45c1b815c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  23:        0x1028c8314 - std::panic::catch_unwind::hbdeff70f3984ee7b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  24:        0x1028c8314 - std::rt::lang_start_internal::{{closure}}::haa4994ba13a3cd15
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:48
  25:        0x1028c8314 - std::panicking::try::do_call::h39b55541875d339a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  26:        0x1028c8314 - std::panicking::try::h93ac0a218f84acad
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  27:        0x1028c8314 - std::panic::catch_unwind::h07a4f62359dfd8f0
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  28:        0x1028c8314 - std::rt::lang_start_internal::hdd06e3566639fc5b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:20
  29:        0x1028478a8 - _main

```

**Comment by mdrokz** [comment]
> Can't utilize GPU on Mac with
> 
> ```
> llama_cpp_rs = { git = "https://github.com/mdrokz/rust-llama.cpp", version = "0.3.0", features = [
>     "metal",
> ] }
> ```
> 
> Code
> 
> ```
> use llama_cpp_rs::{
>     options::{ModelOptions, PredictOptions},
>     LLama,
> };
> fn main() {
>     let model_options = ModelOptions {
>         n_gpu_layers: 1,
>         ..Default::default()
>     };
> 
>     let llama = LLama::new("zephyr-7b-alpha.Q2_K.gguf".into(), &model_options);
>     println!("llama: {:?}", llama);
>     let predict_options = PredictOptions {
>         tokens: 0,
>         threads: 14,
>         top_k: 90,
>         top_p: 0.86,
>         token_callback: Some(Box::new(|token| {
>             println!("token1: {}", token);
> 
>             true
>         })),
>         ..Default::default()
>     };
> 
>     llama
>         .unwrap()
>         .predict(
>             "what are the national animals of india".into(),
>             predict_options,
>         )
>         .unwrap();
> }
> ```
> 
> Error
> 
> ```
> llama_new_context_with_model: kv self size  =   64.00 MB
> llama_new_context_with_model: ggml_metal_init() failed
> llama: Err("Failed to load model")
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to load model"', src/main.rs:40:10
> ```

Hmm weird i dont have a mac available currently to test this, i will try to see about this. Thanks

**Comment by zackshen** [comment]
i have the same problem on my Apple M1.

**Comment by zackshen** [comment]
@phudtran i have found root cause. you should put the `ggml-metal.metal` file  next to your binary. i found  disable the debug log print  `build.rs` for building metal feature. so print more log to find the error.

build.rs 
```rust
fn compile_metal(cx: &mut Build, cxx: &mut Build) {
    cx.flag("-DGGML_USE_METAL").flag("-DGGML_METAL_NDEBUG");
    cxx.flag("-DGGML_USE_METAL");

    println!("cargo:rustc-link-lib=framework=Metal");
    println!("cargo:rustc-link-lib=framework=Foundation");
    println!("cargo:rustc-link-lib=framework=MetalPerformanceShaders");
    println!("cargo:rustc-link-lib=framework=MetalKit");

    cx.include("./llama.cpp/ggml-metal.h")
        .file("./llama.cpp/ggml-metal.m");
}
```

disable `GGML_METAL_NDEBUG`
```rust
fn compile_metal(cx: &mut Build, cxx: &mut Build) {
    cx.flag("-DGGML_USE_METAL"); // <==============    like this 
    cxx.flag("-DGGML_USE_METAL");

    println!("cargo:rustc-link-lib=framework=Metal");
    println!("cargo:rustc-link-lib=framework=Foundation");
    println!("cargo:rustc-link-lib=framework=MetalPerformanceShaders");
    println!("cargo:rustc-link-lib=framework=MetalKit");

    cx.include("./llama.cpp/ggml-metal.h")
        .file("./llama.cpp/ggml-metal.m");
}
```

**Comment by hugonijmek** [comment]
@zackshen I've tried adding the `ggml-metal.metal` file next to the binary, but now I get the following message:
`-[MTLComputePipelineDescriptorInternal setComputeFunction:withType:]:722: failed assertion 'computeFunction must not be nil.'`

**Comment by zackshen** [comment]
> @zackshen I've tried adding the `ggml-metal.metal` file next to the binary, but now I get the following message:
> 
> `-[MTLComputePipelineDescriptorInternal setComputeFunction:withType:]:722: failed assertion 'computeFunction must not be nil.'`

I modified the example code in 
 the this repo for testing gpu
 utilization. Can you show your source code ?

**Comment by mdrokz** [comment]
> @phudtran i have found root cause. you should put the `ggml-metal.metal` file next to your binary. i found disable the debug log print `build.rs` for building metal feature. so print more log to find the error.
> 
> build.rs
> 
> ```rust
> fn compile_metal(cx: &mut Build, cxx: &mut Build) {
>     cx.flag("-DGGML_USE_METAL").flag("-DGGML_METAL_NDEBUG");
>     cxx.flag("-DGGML_USE_METAL");
> 
>     println!("cargo:rustc-link-lib=framework=Metal");
>     println!("cargo:rustc-link-lib=framework=Foundation");
>     println!("cargo:rustc-link-lib=framework=MetalPerformanceShaders");
>     println!("cargo:rustc-link-lib=framework=MetalKit");
> 
>     cx.include("./llama.cpp/ggml-metal.h")
>         .file("./llama.cpp/ggml-metal.m");
> }
> ```
> 
> disable `GGML_METAL_NDEBUG`
> 
> ```rust
> fn compile_metal(cx: &mut Build, cxx: &mut Build) {
>     cx.flag("-DGGML_USE_METAL"); // <==============  enable print debug log.
>     cxx.flag("-DGGML_USE_METAL");
> 
>     println!("cargo:rustc-link-lib=framework=Metal");
>     println!("cargo:rustc-link-lib=framework=Foundation");
>     println!("cargo:rustc-link-lib=framework=MetalPerformanceShaders");
>     println!("cargo:rustc-link-lib=framework=MetalKit");
> 
>     cx.include("./llama.cpp/ggml-metal.h")
>         .file("./llama.cpp/ggml-metal.m");
> }
> ```
> 
> @mdrokz Should add some flags to enable(disable) the debug log ?

I will add an option for enabling / disabling debug

**Comment by genbit** [comment]
Encountered the same error. Placing ggml-metal.metal into the project directory leads to the same error as @hugonijmek have seen. 

However, this solves the original issue: setting the following env variable to point to llama.cpp sources GGML_METAL_PATH_RESOURCES=/rust-llama.cpp/llama.cpp/ solves the issue. (https://github.com/ggerganov/whisper.cpp/blob/master/ggml-metal.m#L261)

**Comment by tbogdala** [comment]
If you want to include it in the build so you don't have to worry about having the shader file parallel or using the environment variable, you can use the solution from the rustformers/llm respository:
https://github.com/rustformers/llm/commit/9d39ff8cc0a89bb22cc17bdc1dd2470f3421d788

To get it working, update the needle to the current string. 

The file this puts in the output directory has a prefix to 'ggml-metal.o' so when checking the `ggml_type` in `compile_llama`, check for "metal" and if so, search the directory for the file using a call to `ends_with("-ggml-metal.o")` and then add that with `cxx.object(metal_path)`.
